# Generated by Django 3.0.10 on 2021-07-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commision_calculator', '0002_reservations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='city',
            field=models.CharField(max_length=25),
        ),
    ]
